module.exports.hotpepper = {
  id: true,
  name: true,
  name_kana: true,
  latitude: 'lat',
  longitude: 'lng',
  url: 'urls.pc',
  url_mobile: 'urls.pc',
  images: ['photo.pc.l'],
  coupon_url: { desktop: 'coupon_urls.pc', mobile: 'coupon_urls.sp' },
  tel: null,
  opening_times: 'open',
  catchphrase: 'catch',
  description: 'shop_detail_memo',
  access: true,
  holiday: 'close',
  credit_card: 'card',
  non_smoking: true,
  lunch: true,
  children: 'child',
}

module.exports.gurunavi = {
  id: true,
  name: true,
  name_kana: true,
  latitude: true,
  longitude: true,
  url: true,
  url_mobile: true,
  images: ['image_url.shop_image1', 'image_url.shop_image2'],
  coupon_url: { desktop: 'coupon_url.pc', mobile: 'coupon_url.mobile' },
  tel: true,
  opening_times: 'opentime',
  catchphrase: 'pr.pr_short',
  description: 'pr.pr_long',
  access: 'access.line,access.station,access.station_exit,access.walk,access.note',
  holiday: true,
  credit_card: true,
  non_smoking: null,
  lunch: true,
  children: null,
}
