version: 2

references:
  container_base_config: &container_base_config
    docker:
      - image: node:8.11.3
    working_directory: ~/remap-app/restraunts

jobs:
  test:
    <<: *container_base_config
    steps:
      - checkout
      - run:
          name: Tests
          command: yarn test

workflows:
  version: 2
  production_deploy:
    jobs:
      - test
    filters:
      branches:
        only:
          - deployment/production
